### ISSUE TITLE
Non YouTube and changing channels 

### ISSUE THREAD

**Issue by upintheairsheep2** [mrpapersonic/yt-archive#2]
I need help. I’ve been trying to modify the code to work on non YouTube sites yt-dlp supports and attempting to change the channels from those anime channels.

**Comment by mrpapersonic** [comment]
All this code does is go through a list of channel IDs and put them into an upload script (that ignores errors). The IA email and password are stored through secrets in the repository settings.

Changing the channels is simple, adding support for other websites would be easy too; remove the "https://youtube.com/channel/" part of the code that tells tubeup that it's a YouTube channel, and use the full links of the channels in the list.
